spring:
  application:
    name: core
  jpa:
    open-in-view: false
    hibernate:
      properties:
        enable_lazy_load_no_trans: true
        hibernate:
          jdbc.time_zone: UTC
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/core?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    user: root
    username: root
    password: admin
  jackson:
    default-property-inclusion: non_null

  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379

logging:
  file: /logs/application.log
  level:
    root: WARN
    org.springframework: WARN
    com.homer: INFO
    in: WARN
    out: WARN

app:
  kafkaUrl: localhost:9092
  clusterId: ${spring.application.name}
  maxThread: 4
  consumerCount: 3
  defaultPage: 0
  defaultPageSize: 20
  timeModify: 3600
  descriptionMaxLength: 2500
  timeStampHash: 30000
  topics:
    userInfo: user-info
    notification: notification
    pushNotification: push-notification
    syncRedisMysql: sync-redis-mysql
  aes:
    key: SWFQT044clhqQ1E1VElVVllCdGN3OFdLR0NmY1FFdGM=
    iv: TmNSZlVqV25acjR1N3ghQQ==
    keyHash: wfyxb3sR1O

