spring:
  application:
    name: core
  jpa:
    open-in-view: false
    hibernate:
      properties:
        enable_lazy_load_no_trans: true
        hibernate:
          jdbc.time_zone: UTC
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/core?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    user: root
    username: root
    password: admin
  jackson:
    default-property-inclusion: non_null

  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379

logging:
  file: /logs/application.log
  level:
    root: WARN
    org.springframework: WARN
    com.homer: INFO
    in: WARN
    out: WARN

app:
  kafkaUrl: localhost:9092
  clusterId: ${spring.application.name}
  maxThread: 4
  consumerCount: 3
  defaultPage: 0
  defaultPageSize: 20
  timeModify: 3600
  descriptionMaxLength: 2500
  topics:
    userInfo: user-info
    notification: notification
    pushNotification: push-notification
    syncRedisMysql: sync-redis-mysql
  vnPay:
    vnpVersion: 2.1.0
    vnpCommand: pay
    vnpCurrCode: VND
    vnpLocale: vn
    datePattern: yyyyMMddHHmmss
    vnPayAmountRate: 100
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    expireTime: 3600
    orderType: ""
    paymentInfo:
      returnUrl: ""
      secureHash: ""
      tmnCode: ""
    depositInfo:
      returnUrl: ""
      secureHash: ""
      tmnCode: ""




