package com.homer.core.common.constants;

public enum ErrorCodeEnums {
    INTERNAL_SERVER_ERROR,
    INVALID_PARAMETER,
    URI_NOT_FOUND,
    INVALID_VALUE,
    EMPTY_VALUE,
    VALUE_MUST_EQUAL,
    VALUE_MUST_LESS_OR_EQUAL,
    VALUE_MUST_GREATER,
    VALUE_MUST_GREATER_OR_EQUAL,
    VALUE_MUST_LESS,
    VALUE_MUST_IN,
    INVALID_FORMAT
}
